# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      output_types: 'junit,html',
      scheme: "Project1",
      output_directory: "scan",
      buildlog_path: "logs",
      code_coverage: true,
      derived_data_path: "derived_data"
    )
  end

  desc "Runs Code Coverage"
  lane :coverage do
    # Add targets here as you create internal frameworks
    xcov_scheme = "Project1"

    xcov(
      scheme: xcov_scheme,
      output_directory: "xcov",
      json_results: true,
      derived_data_path: "derived_data"
    )
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end
end
